//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by shaderdbeditor.rc
//
#define IDC_MYICON                      2
#define IDI_ICON1                       101
#define IDR_MYMENU                      101
#define IDD_SHADERDBEDITOR_DIALOG       102
#define ID_ASSETC_IMPORT_GENERIC_DATA   102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDS_HELLO                       106
#define IDD_PROPPAGE_MEDIUM             106
#define IDI_SHADERDBEDITOR              107
#define IDI_SMALL                       108
#define IDC_SHADERDBEDITOR              109
#define IDI_DATAGRIDTEST                110
#define IDC_DATAGRIDTEST                111
#define IDR_MAINFRAME                   128
#define IDC_LIST1                       1001
#define IDC_BUTTON2                     1002
#define IDC_OUTPUT_FILE                 1003
#define IDC_NLODS_SELECTOR              1004
#define IDC_MANUAL_BBOX                 1005
#define IDC_BBOX_XMIN                   1006
#define IDC_BBOX_YMIN                   1007
#define IDC_BBOX_ZMIN                   1008
#define IDC_BBOX_XMAX                   1009
#define IDC_BBOX_YMAX                   1010
#define IDC_BBOX_ZMAX                   1011
#define IDC_EDIT9                       1013
#define IDC_EDIT10                      1014
#define IDC_EDIT11                      1015
#define IDC_EDIT12                      1016
#define IDC_EDIT1                       1017
#define IDC_ASSETC_MESH_DBX_FILE        1017
#define IDC_ASSETC_LODS_FILE            1018
#define ID_FILE_EXIT                    9001
#define ID_TREEVIEW                     9002
#define ID_FILE_OPEN                    9003
#define ID_FILE_CLOSE                   9004
#define ID_EXPORT_DB                    9005
#define ID_EXPORT_HLSL                  9006
#define ID_SHADER_VIEW                  9007
#define ID_TXE_VIEW                     9008
#define ID_D3DPARAMS1_VIEW              9009
#define ID_D3DPARAMS2_VIEW              9010
#define ID_VERTEXSHADER_VIEW            9011
#define ID_PIXELSHADER_VIEW             9012
#define ID_TABLES_VIEW                  9013
#define ID_VBUFFERS_VIEW                9014
#define ID_STRINGS_VIEW                 9015
#define ID_TEXTURELIST                  9016
#define ID_VS_HLSL_SHADER               9017
#define ID_TABLE                        9018
#define ID_VX_STANDARD                  9019
#define ID_VX_STREAM                    9020
#define ID_VX_OTHER                     9021
#define ID_STR_REF                      9022
#define ID_SHADER_NODE                  9023
#define ID_MESH_NODE                    9024
#define ID_STR_MESH_REF                 9025
#define ID_STR_SHDR_REF                 9026
#define TYPE_INT32                      9032
#define TYPE_UINT32                     9033
#define TYPE_FLOAT                      9034
#define TYPE_TEXT                       9035
#define TYPE_GUID                       9036
#define TYPE_TITLE                      9048
#define TYPE_HEX                        9049
#define TEXTURE_NAME                    9050
#define PARAM_NAME                      9051
#define MEMBER_TYPE                     9052
#define ID_LISTVIEW                     9057
#define ID_EDIT_ENABLE                  9100
#define ID_SHADERS_P_NODE               9101
#define ID_SYSTEMS_P_NODE               9102
#define ID_SYSTEMS_N_NODE               9103
#define ID_MESH_P_NODE                  9104
#define ID_UPDATE_LV                    9130
#define ENABLE_UPD_BTN                  9131
#define ID_CLONE_TXE                    9132
#define ID_EXPORT_STR                   9133
#define ID_IMPORT_DB                    9134
#define ID_SAVE_DB                      9135
#define ID_PS_HLSL_SHADER               9136
#define ID_ASSETC_START                 9140
#define UM_CHECKSTATECHANGE             9141
#define ID_ASSETC_OPEN_SET              9200
#define ID_ASSETC_SAVE_SET              9201
#define ID_ASSETC_EXPORT_MESH           9202
#define ID_ASSETC_IMPORT_MESH           9203
#define ID_ASSETC_OPEN_MESHDATA         9204
#define ID_ASSETC_OPEN_FBX              9205
#define ID_ASSETC_EXPORT_START          9206
#define ID_ASSETC_IMPORT_MESH_TAB       9207
#define SHOW_EXPORT_LOD                 9300
#define SHOW_EXPORT_START_BTN           9301
#define ID_ASSETC_OPEN_MESHDATA_LOD0    9302
#define ID_ASSETC_OPEN_MESHDATA_LOD1    9303
#define ID_ASSETC_OPEN_MESHDATA_LOD2    9304
#define ID_ASSETC_OPEN_MESHDATA_LOD3    9305
#define ID_ASSETC_IMPORT_DATA_WRAPPER   9400
#define ID_ASSETC_IMPORT_DATA_TEXT1     9401
#define ID_ASSETC_IMPORT_DATA_TEXT2     9402
#define ID_ASSETC_IMPORT_DATA_TEXT3     9403
#define ID_ASSETC_IMPORT_DATA_TEXT4     9404
#define ID_ASSETC_IMPORT_DATA_TEXT5     9405
#define ID_ASSETC_IMPORT_DATA_OUTPUT_EDIT    9406
#define ID_ASSETC_IMPORT_DATA_LODS_COMBO     9407
#define ID_ASSETC_IMPORT_DATA_R01     9408
#define ID_ASSETC_IMPORT_DATA_R02     9410
#define ID_ASSETC_IMPORT_DATA_R03     9411
#define ID_ASSETC_IMPORT_DATA_R04     9412
#define ID_ASSETC_IMPORT_DATA_MESHDBX_EDIT    9413
#define ID_ASSETC_IMPORT_DATA_LODSFILE_EDIT    9414
#define ID_ASSETC_IMPORT_DATA_BBOX_ENABLE    9415
#define ID_ASSETC_IMPORT_DATA_XMIN    9416
#define ID_ASSETC_IMPORT_DATA_YMIN    9417
#define ID_ASSETC_IMPORT_DATA_ZMIN    9418
#define ID_ASSETC_IMPORT_DATA_XMAX    9419
#define ID_ASSETC_IMPORT_DATA_YMAX    9420
#define ID_ASSETC_IMPORT_DATA_ZMAX    9421
#define ID_ASSETC_IMPORT_DATA_TG_SEL  9422
#define ID_ASSETC_IMPORT_DATA_BILLBOARD  9423
#define ID_ASSETC_IMPORT_DATA_VX1  9424
#define ID_ASSETC_IMPORT_DATA_VX2  9425
#define ID_ASSETC_IMPORT_START  9426
#define ID_ASSETC_IMPORT_DATA_BBOARD_ENABLE  9427
#define ID_ASSETC_ENABLE_MENU_BTN     9500
#define ID_ASSETC_CREATE_SET            9501
#define ID_ASSETC_EXTRACT_SET            9502
#define ID_ASSETC_EXTRACT_MESHDATA_INFO  9503

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1019
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
